# vim:ft=ansible:
---
- name: Install XCode CLI Tools
  shell: xcode-select --install

- name: Install Homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

- name: Update Homebrew
  shell: brew update; brew upgrade

- name: Install Homebrew Cask
  shell: brew install caskroom/cask/brew-cask

- name: Install Utility packages from Homebrew
  homebrew: name={{item}} state=present
  with_items: utility

- name: Install Language packages from Homebrew
  homebrew: name={{item}} state=present
  with_items: language

- name: Upgrade Pip and Setuptools
  pip: name={{item}} state=latest
  with_items:
  - pip
  - setuptools

- name: Install Virtualenv
  pip: name=virtualenv state=latest

- name: Install App packages from Homebrew
  homebrew: name={{item}} state=present
  with_items: app

- name: Install Desktop Apps
  shell: brew cask install {{ item }}
  with_items: desktop

- name: Create screenshot directory
  file: path=~/Pictures/screenshots state=directory

- name: Change Screenshot location
  shell: defaults write com.apple.screencapture location ~/Pictures/screenshots;killall SystemUIServer
