# vim:ft=ansible:
---
- name: Update Homebrew
  shell: brew update; brew upgrade

- name: Tap Homebrew Versions
  shell: brew tap homebrew/versions

- name: Tap Homebrew rmtree
  shell: brew tap beeftornado/rmtree

- name: Make Standard Directories
  file: path={{item}} state=directory mode=0755
  with_items:
    - ~/tmp
    - ~/go
    - ~/src
    - ~/bin
    - ~/envs
    - ~/repos
    - ~/.vim_swap
    - ~/.vim_undo

- name: Install Utility packages from Homebrew
  homebrew: name={{item.pkg}} state={{item.state}} install_options={{item.options}}
  with_items: utility

- name: Install Language packages from Homebrew
  homebrew: name={{item.pkg}} state={{item.state}} install_options={{item.options}}
  with_items: language

- name: Install Python Packages
  pip: name={{item}} state=latest
  with_items: python

- name: Install App packages from Homebrew
  homebrew: name={{item.pkg}} state={{item.state}} install_options={{item.options}}
  with_items: app

- name: Install Desktop Apps
  homebrew_cask: name={{item.pkg}} state=present
  with_items: desktop

- name: Install Work Desktop Apps
  homebrew_cask: name={{item.pkg}} state=present
  with_items: work_desktop

- name: Download Source Code Pro
  get_url: url=https://github.com/adobe-fonts/source-code-pro/archive/2.010R-ro/1.030R-it.tar.gz dest=~/tmp/scp.tar.gz

- name: Unarchive Source Code Pro
  unarchive: src=~/tmp/scp.tar.gz dest=~/tmp

- name: Install Source Code Pro
  shell: mv ~/tmp/source-code-pro-2.010R-ro-1.030R-it/OTF/*.otf ~/Library/Fonts/

- name: Clone Vundle
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim

- name: Install VIM plugins
  shell: vim +PluginInstall +qall

- name: Create screenshot directory
  file: path=~/Dropbox/screenshots state=directory

- name: Change Screenshot location
  shell: defaults write com.apple.screencapture location ~/Dropbox/screenshots;killall SystemUIServer

- name: Create locate database
  shell: launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist become=yes

- name: Install Freetds for Azure
  homebrew: name=freetds state=present install_options=with-unixodbc
