# vim:ft=ansible:
---

- name: update homebrew
  shell: brew update; brew upgrade

- name: tap homebrew
  shell: brew tap "{{item}}"
  with_items: "{{taps}}"

- name: install desktop apps
  homebrew_cask: name="{{item}}" state=present
  with_items: "{{desktop|union(work_desktop)}}"
