# vim:ft=ansible:
---

- name: update homebrew
  shell: brew update; brew upgrade

- name: tap homebrew
  shell: brew tap "{{item}}"
  with_items: "{{taps}}"

- name: install utility packages
  homebrew: name="{{item.pkg}}" state="{{item.state}}" install_options="{{item.options|default(omit)}}"
  with_items: "{{utility|union(work_utility) }}"

- name: install languages
  homebrew: name="{{item.pkg}}" state="{{item.state}}" install_options="{{item.options|default(omit)}}"
  with_items: "{{language}}"

- name: install app packages from homebrew
  homebrew: name="{{item.pkg}}" state="{{item.state}}" install_options="{{item.options|default(omit)}}"
  with_items: "{{apps}}"

- name: install fonts
  homebrew_cask: name="{{item}}" state=installed
  with_items: "{{fonts}}"

- name: Change Screenshot location
  shell: defaults write com.apple.screencapture location "{{screenshot_directory}}";killall SystemUIServer

- name: Create locate database
  shell: launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist become=yes
